name: gitops-CI

on: 
  push:
  pull_request:
  # manual trigger
  workflow_dispatch:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.57
  build:
    name: build
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_POSTGRES_HOST: postgresdb
          ENV_POSTGRES_PORT: 5432
          ENV_POSTGRES_DB: mydatabase
          ENV_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          ENV_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Start Docker Compose services
        run: |
          docker-compose up --build -d
          docker-compose ps
  
      - name: Run tests
        id: test
        run: docker-compose run backend go test -v ./tests/...
      
      - name: Check test results
        run: |
          test_result=$(echo "${{ steps.test.outputs.run }}" | tail -n 1)
          if [[ $test_result == *"[no test files]"* ]]; then
            echo "No tests to run. Skipping image push."
            exit 0
          fi

      - name: Login to Docker Hub
        if: ${{ success() }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Push docker image if integration test passes
        if: ${{ success() }}
        run: docker compose push
      
      - name: Stop Docker Compose services
        run: docker-compose down

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to DockerHub via Helm
        uses: central-x/helm-login-action@v1
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      
      - name: Push Helm Chart
        uses: central-x/helm-push-action@v1
        with:
          repository: oci://registry-1.docker.io/${{ secrets.USERNAME }}
          chart: ./f2pool-chart