name: gitops-CI

on: 
  push:
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    name: build
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_POSTGRES_HOST: postgresdb
          ENV_POSTGRES_PORT: 5432
          ENV_POSTGRES_DB: mydatabase
          ENV_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          ENV_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Start Docker Compose services
        run: |
          docker-compose up --build -d
          docker-compose ps
  
      - name: Run tests
        run: docker-compose run backend go test -v -tags=unit,integration -coverprofile=coverage.out ./tests/*
  
      - name: Stop Docker Compose services
        run: docker-compose down

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: build and push docker image
        run: docker compose build && docker compose push

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to DockerHub via Helm
        uses: central-x/helm-login-action@v1
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      
      - name: Push Helm Chart
        uses: central-x/helm-push-action@v1
        with:
          repository: oci://registry-1.docker.io/${{ secrets.USERNAME }}
          chart: ./f2pool-chart